name: feed
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # stacked state management
  stacked: ^2.2.3
  stacked_services: ^0.8.13
  observable_ish: ^3.0.0

  # data models
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1

  # logger for debugging
  logger: ^1.0.0

  # checks connectivity - [mobile][wifi][offline]
  connectivity: ^3.0.3

  # A secure internal NoSQL Database
  hive: ^2.0.4
  path_provider: ^2.0.1
  shared_preferences: ^2.0.6

  # graphql for fetching data from API
  graphql: ^5.0.0-nullsafety.4

  # could be handy for hiding keys in [.env] file
  flutter_dotenv: ^5.0.0

  # fetches [version][build-info]..
  package_info: ^2.0.0

  # a videoplayer to play youtube videos
  flick_video_player: ^0.3.1
  share: ^2.0.1
  youtube_explode_dart: ^1.9.4
  visibility_detector: ^0.2.0

  # firebase integration
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  stacked_firebase_auth: ^0.2.8
  firebase_dynamic_links: ^2.0.7
  firebase_crashlytics: ^2.1.1
  firebase_analytics: ^8.2.0
  firebase_messaging: ^10.0.4
  awesome_notifications: ^0.0.6+10
  
  inview_notifier_list: ^2.0.0
  flutter_hooks: ^0.18.0
  url_launcher: ^6.0.9
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  # code generators
  build_runner:
  stacked_generator: ^0.5.2
  hive_generator: ^1.1.0

  # data models
  freezed: ^0.14.1+3
  json_serializable: ^5.0.0

  # for testing
  mockito:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Regular.otf
          weight: 400
        - asset: assets/fonts/Medium.otf
          weight: 500
        - asset: assets/fonts/Semibold.otf
          weight: 600
        - asset: assets/fonts/Bold.otf
          weight: 700
        - asset: assets/fonts/Heavy.otf
          weight: 800
        - asset: assets/fonts/Black.otf
          weight: 900
