name: feed
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+9

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  # stacked state management
  stacked:
    git:
      url: https://github.com/amanxnanda/stacked
      path: packages/stacked
  stacked_services:
    git:
      url: https://github.com/amanxnanda/stacked
      path: packages/stacked_services
  observable_ish: ^3.0.0

  # data models
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0

  # logger for debugging
  logger: ^1.1.0

  # checks connectivity - [mobile][wifi][offline]
  connectivity: ^3.0.6

  # A secure internal NoSQL Database
  hive: ^2.0.4
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8

  # graphql for fetching data from API
  graphql: ^5.0.0

  # network
  dio: ^4.0.0

  # could be handy for hiding keys in [.env] file
  flutter_dotenv: ^5.0.2

  # fetches [version][build-info]..
  package_info: ^2.0.2

  # a videoplayer to play youtube videos
  # flick_video_player: ^0.3.1
  flick_video_player: ^0.4.0-dev.4
  share: ^2.0.4
  youtube_explode_dart: ^1.10.8
  visibility_detector: ^0.2.0

  # firebase integration
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  stacked_firebase_auth: ^0.2.10
  firebase_dynamic_links: ^2.0.9
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^8.3.2
  firebase_messaging: ^10.0.7
  awesome_notifications: ^0.0.6+10

  inview_notifier_list: ^2.0.0
  flutter_hooks: ^0.18.0
  url_launcher: ^6.0.11
  intl: ^0.17.0

  lottie: ^1.2.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  # code generators
  build_runner:
  stacked_generator:
    git:
      url: https://github.com/amanxnanda/stacked
      path: packages/stacked_generator
  hive_generator: ^1.1.1

  # data models
  freezed: ^0.14.5
  json_serializable: ^5.0.0

  # for testing
  mockito:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Regular.otf
          weight: 400
        - asset: assets/fonts/Medium.otf
          weight: 500
        - asset: assets/fonts/Semibold.otf
          weight: 600
        - asset: assets/fonts/Bold.otf
          weight: 700
        - asset: assets/fonts/Heavy.otf
          weight: 800
        - asset: assets/fonts/Black.otf
          weight: 900
