name: Generate Release Articraft

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Playstore Signing
        run: cd ./android && echo '${{ secrets.PLAY_STORE_SIGNING }}' > key.properties

      - name: Import Firebase Settings
        run: cd ./android/app && echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"

      - name: Init Flutter
        run: flutter doctor -v && flutter pub get
      
      - name: Code Analysis
        run: flutter analyze

      - run: flutter build apk --release

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.0.1+${{ github.run_number }}